# python dino2yolo_dataset.py --config_path configs/Kolchugino4__2024_11_26__16_23_14.yml

CHUNK: Kolchugino4__2024_11_26__16_23_14
ROOT: !ref /home/ubuntu/DMITRII/EmbleMLDev3.0/datasets/ObjectDetection/<CHUNK>/yolo_<CHUNK>
CLASSES: ['person', 'horse', 'other_animal']
GDINO_ARGS_PATH: /home/ubuntu/DMITRII/EmbleMLDev3.0/GroundingDINO/src/gdino_config_01.yaml

PREDICTOR_KWARGS: {
  root: !ref <ROOT>,
  classes: !ref <CLASSES>,
  gdino_args_path: !ref <GDINO_ARGS_PATH>
}